### ISSUE TITLE
Bootstrap React component and repository

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#1]
**What needs to be done? Why does it need to be done?**
Add the basic infrastructure needed to create a React component in version control. The deliverable artifact here is simply a React component that can be dropped into a separate application. However, it's important to be able to test this ourselves, so we need some minimal "app" that we can drop the component into and run _locally_ for testing. 

**Additional context**
We don't need any infrastructure for hosting or deploys. We just need to be able to run/test the component (and sub-components that get created).

**Comment by Wmaileq** [comment]
@jessex Maybe this component should be delivered as yarn\npm package that easily could be integrated in any project?
Or it will be just one release of this component and customers will just copy and paste code to theirs repo?

**Comment by jessex** [comment]
I think it is unlikely to see significant ongoing development after launch, but it does raise a good question, regardless, about the right way to package this up. I'll reach out to them and ask--we don't need to know the answer to this yet, but if it turns out that an npm package is the right way to go then I'll file a task for the end to bundle this up.
