### ISSUE TITLE
[Polish] Ensure good user experience in all targeted environments

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#11]
**What needs to be done? Why does it need to be done?**
As documented in the [PRD](https://docs.google.com/document/d/1vssQ4JB8VyfInFpdw7F_4laQG0WVXYv6u4FwIpIFUoQ/edit?ts=5f58fbbc#heading=h.c29ll7o2tvsa), we want this to have a good look-and-feel and work as intended in a given set of browsers, including IE11, and on mobile. We should use Browserstack to test the app in all desired environments and fix any identified issues in this ticket or in new tickets for specific issues.

**Additional context**
N/A

**Comment by jessex** [comment]
@Wmaileq, this ticket was mistakenly never added to the project board, but it _should_ be a superset of the work you've already done with mobile and IE11. Essentially, you should do a pass through all of the browsers explicitly mentioned in the PRD and make sure this looks and functions as expected. If everything is good to go and no PR is needed, just comment on this ticket and we'll close it. Thanks!

**Comment by Wmaileq** [comment]
@jessex as today i have checked application in IOS safari, chrome and IE11 the 2 browsers left are: firefox and edge. So i will check soon and reply.

**Comment by Wmaileq** [comment]
@jessex checked in firefox and edge, all works as expected

**Comment by jessex** [comment]
Thanks for the confirmation, @Wmaileq!
