### ISSUE TITLE
The [Maintain 2020 levels] button always uses the same hard-coded 2020 reduction amounts

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/supervision-success-component#117]
**Describe the bug**
On all states, clicking the [Maintain 2020 levels] in the banner always adjusts the sliders in the same way - (-21%) for revocations, and (-14%) for new admissions. This is my fault for being unclear in the initial feature request. 

What we want want is for that button to set the sliders, so that the state maintains at the 2020 levels of both admissions and revocations. That will be a different amount, for each slider, in every state.  

**To Reproduce**
1. Go to any state
2. Click the banner button, 'Maintain 2020 levels'
3. Note that the sliders jump to -21% / -14%
4. This is consistent on all states

**Expected behavior**
When the 'Maintain 2020 levels' button is clicked, the sliders should jump to the percent reduction that 2020 is below 2019 for both Revocations and Admissions.

**Comment by cawarren** [comment]
Note to Ilya: I'm looking through the data inputs and the model, and I can't tell if you have enough information to know which toggle contributes how much to the overall population reduction from 2019 to 2020 based on the inputs.

If you don't, I suggest we simply remove the two buttons for now and change the banner text to the following:

> This model estimates the change in prison population over time if supervision revocations and new admissions return to 2019 levels. Use the sliders below to model the outcomes of maintaining 2020 levels, or to test out other scenarios.

**Comment by jessex** [comment]
That was definitely a big misunderstanding -- Ilya and I both thought you wanted -21 and -14 reductions.

**Comment by cawarren** [comment]
I'm sorry about that, it's completely on me for being ambiguous / not
putting enough thought into the description.

Thanks for the quick reaction on this Josh.
