### ISSUE TITLE
High-level security vulnerability: set-value

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/supervision-success-component#125]
**What needs to be done? Why does it need to be done?**
A high-level security vulnerability has been detected by Dependabot in this project.

Per our SLA, high-level security vulnerabilities need to be addressed within 30 days. The deadline for resolution is October 17, 2021.

**Additional context**
https://github.com/Recidiviz/supervision-success-component/security/dependabot/yarn.lock/set-value/open

**Comment by jessex** [comment]
It seems that this alert was resolved upstream of us -- this was a _deep_ transitive dependency, several layers removed, brought in by a direct dependency on some core React packages. Somewhere in that chain of dependencies, the set-value version was upgraded and the alert was resolved on our behalf.

Closing this out!
