### ISSUE TITLE
Create skeleton of the page/component

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#3]
**What needs to be done? Why does it need to be done?**
First, build the general skeleton of the app as described in the [PRD](https://docs.google.com/document/d/1vssQ4JB8VyfInFpdw7F_4laQG0WVXYv6u4FwIpIFUoQ/edit?ts=5f58fbbc#). This does not need to have full interaction yet and does not need the model/data file. We just want to have the basic UI in place (everything below the header) with the requisite sub-components that we intend to fill in, and want to ensure that the basic UI looks reasonable in the browsers/environments documented in the PRD.

**Additional context**
Later tasks will fill in the interactive functionality and data modeling.

**Comment by Wmaileq** [comment]
Was closed by #12
