### ISSUE TITLE
Implement selection elements - state, implementation period, projections

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#4]
**Is your feature request related to a problem? Please describe.**
As described in the [PRD](https://docs.google.com/document/d/1vssQ4JB8VyfInFpdw7F_4laQG0WVXYv6u4FwIpIFUoQ/edit?ts=5f58fbbc#heading=h.c29ll7o2tvsa), there are a number of interactive elements used in the component. We should implement the three along the top of the central component all at once: the state selector, the implementation period selector, and the projection selector.

**Describe the solution you'd like**
They should have the same exact look-and-feel, as displayed by the implementation period selector in the mock, although the font for the chosen state is larger than the others. They do not yet need to be hooked into any other logic -- that will get implemented in future tasks -- but you should be able to interact with the menus and make selections.

**Describe alternatives you've considered**
N/A

**Additional context**
This does not include the revocation slider, which will be in a separate task.

**Comment by Wmaileq** [comment]
Was closed in #12
