### ISSUE TITLE
Adjust cost calculation to include fixed-costs ("checkpoints") with revocation increases as well 

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/supervision-success-component#49]
**Is your feature request related to a problem? Please describe.**
In the web component, a user can increase or decrease revocations (individuals removed from community supervision and sent to prison). The component calculates the amount that it will cost (or that will be saved) if revocations go up or down.

Currently, if revocations go **down** then the savings is calculated both using a 'Marginal cost per inmate' and adding in the 'associated savings' at each of several checkpoints. These checkpoints represent a facility being closed.

However, when revocations go **up** we only increase marginal costs - we do not add the fixed costs for new facilities as the population in prison increases (see attached images - note that costs increase at a much slower rate than savings).

**Describe the solution you'd like**
We'd like to use the same checkpoints and associated savings for revocations going up. That is, we use marginal costs until we hit a checkpoint, and then costs increase by that checkpoint amount - then costs continue to rise by the marginal cost per inmate until we hit the next checkpoint.

**Describe alternatives you've considered**
No alternatives have been considered. We could leave the behavior as-is, but it wouldn't accurately reflect the costs of incarceration.

![fast_increase_in_savings](https://user-images.githubusercontent.com/59526/102266321-48389500-3ee6-11eb-9db6-54d89f8fcfb4.png)
![slow_increase_in_costs](https://user-images.githubusercontent.com/59526/102266323-48d12b80-3ee6-11eb-8578-d96dd7517165.png)

**Comment by jessex** [comment]
@Wmaileq we have a feature request here for the Supervision Success Component project that you worked on a few months ago. Once you've wrapped up the current item you're working on for the Justice Counts Components project, can you tackle this particular issue? We'd like to get this addressed either late this week or next week. Let me know if you have any questions or concerns!

**Comment by alpaco42** [comment]
Hi! I updated the [google sheets version of the model](https://docs.google.com/spreadsheets/d/1hyjxW_713IEhHIZ80UZmkO4jMD8g5VgXDQAo9362ECY/edit#gid=991630608) to reflect the new change. I actually combined this new change with a simplification requested by CSG, i.e. that the "checkpoints" be at regular intervals corresponding to the number of facilities in a state. Thus, the checkpoint/assoicated savings inputs have been removed and replaced with a single "number of facilities" and an additional "state-wide capacity". Let me know if you have any questions about that!

**Comment by alpaco42** [comment]
new schema reflected [here](https://docs.google.com/spreadsheets/d/1BxuuieVPzvjJTpTtRwt9e1d_OJi6hQAvK45mBnSR0d8/edit#gid=991630608)

**Comment by Wmaileq** [comment]
I am almost here, will finish at the start of tomorrow!

**Comment by Wmaileq** [comment]
> Hi! I updated the [google sheets version of the model](https://docs.google.com/spreadsheets/d/1hyjxW_713IEhHIZ80UZmkO4jMD8g5VgXDQAo9362ECY/edit#gid=991630608) to reflect the new change. I actually combined this new change with a simplification requested by CSG, i.e. that the "checkpoints" be at regular intervals corresponding to the number of facilities in a state. Thus, the checkpoint/assoicated savings inputs have been removed and replaced with a single "number of facilities" and an additional "state-wide capacity". Let me know if you have any questions about that!

Hi! 
1. It looks like right now the model for `marginal savings` works not as expected - if you set the `revocation reduction` to a negative number(an increase of revocations) - `total savings` stay positive.
2. Parameter `state wide capacity` is the parameter that shows how much population could be served with `number of facilities` parameter? If so, I think that the model for `total savings` works not as expected too. (Now we calculate integer number of facilities that can be closed\should be opened and multiply it by `total cost per inmate` and by `state wide capacity`, but it looks like we need to multiply not on the whole `state wide capacity` but on `state wide capacity` divided on number of facilities that could be closed/ should be opened)

Please correct me if I'm wrong.

**Comment by alpaco42** [comment]
Great catch, on both fronts! I've updated the google sheet to fix both of these issues (only changes to `marginal savings` and `graduated savings`).  Sorry I didn't validate it carefully enough the first time around!

**Comment by Wmaileq** [comment]
@alpaco42 I've made updates reflecting on changes in excel, 
but one more point: if `state wide capacity === current total population`, does it mean that if we increase the number of people on 1 we need to open one more facility, and graduated savings should be (`total cost * state wide capacity / number of facilities`) starting from the first month?

**Comment by alpaco42** [comment]
That is deliberate. My assumption is that CSG will set them equal the first time they run it and expect the model not to "open a facility" until a substantial increase has occurred. In other words, DOCs air on the side of not opening or closing facilities until they are a full facility over capacity or a full one under.
