### ISSUE TITLE
Resolve security alerts for build tooling

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/supervision-success-component#53]
**What needs to be done? Why does it need to be done?**
~There are two security alerts for transitive dependencies of `react-scripts` that I believe we can safely dismiss.~

~The [alert for `is-svg`](https://github.com/Recidiviz/supervision-success-component/security/dependabot/yarn.lock/is-svg/open) concerns a transitive React-Scripts dependency; it [doesn't sound like](https://github.com/cssnano/cssnano/issues/1019#issuecomment-802182732) there will be a security patch for the line that react-scripts is on (even in the 4.x stream, which we have not upgraded to here). However, according to the maintainers this package is only part of the build tooling and is not actually in use in the bundled application; since there is no actual vulnerability in our deployment I believe this is safe to dismiss.~

~Similarly, [the version of `ssri`](https://github.com/Recidiviz/supervision-success-component/security/dependabot/yarn.lock/ssri/open) included transitively via `webpack` has an issue that [it appears](https://github.com/webpack-contrib/terser-webpack-plugin/issues/388) cannot be resolved without `react-scripts` updating to the next major version of `webpack`. However, this library is only used here as part of the JS minification build tooling and does not get included in the application bundle. It should also be safe to dismiss this as creating no actual vulnerability in the application.~

~Paging @jessex to ratify.~

Update: will attempt to resolve these with version bumps instead; see discussion below

**Additional context**
~There is [a third active alert](https://github.com/Recidiviz/supervision-success-component/security/dependabot/yarn.lock/y18n/open) that Dependabot is still processing but I expect it will be able to resolve that one automatically.~

**Comment by macfarlandian** [comment]
@jessex update on this .... turns out that (a) dependabot failed to resolve the other one automatically for reasons mysterious and (b) I can update all of these via yarn `resolutions` with no apparent issues. so forget about dismissing these for now, PR forthcoming

**Comment by jessex** [comment]
Thanks for keeping me posted, @macfarlandian!
