### ISSUE TITLE
Upgrade vulnerable dependencies ssri and sockjs

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#56]
**What needs to be done? Why does it need to be done?**
There are active dependabot alerts for ssri and sockjs that we should resolve. 
- The alert for ssri says it is no longer vulnerable, but was a high severity alert, so we should look into it all the same
- The sockjs alert is medium vulnerability

Altogether, we should resolve this by next week.

**Additional context**
N/A

**Comment by macfarlandian** [comment]
@jessex we're already on the specified version of `ssri` to resolve the vulnerability and have been since April 1; I'm not sure why dependabot decided to open an alert on this but it is safe to dismiss regardless. PR forthcoming to resolve the other one.

**Comment by jessex** [comment]
That sounds right to me, @macfarlandian! Just approved your PR.
