### ISSUE TITLE
Implement the central chart/visualization

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#6]
**Is your feature request related to a problem? Please describe.**
As described in the [PRD](https://docs.google.com/document/d/1vssQ4JB8VyfInFpdw7F_4laQG0WVXYv6u4FwIpIFUoQ/edit?ts=5f58fbbc#), there is a line graph at the center of the component which is updated based on the various interactive elements around it, and which display the output of the population projection model.

**Describe the solution you'd like**
This chart should be built using either [Semiotic](https://github.com/nteract/semiotic) or [ChartJS](https://www.chartjs.org/), whichever one we think can more easily fit the mocks exactly. The chart should have one line for the baseline population and one line for the output of the projection model. However, the projection model will not have been completed just yet, so we can hard-code fake data for the chart for now.

If it is possible to hook up any of the interactive elements to the chart behavior before the model is in place, we should go ahead and do so. For example, if we can start manipulating the x-axis based on the projections selector then we can do so now.

**Describe alternatives you've considered**
The main choice here is the charting library to use. We should pick whichever one can match the mocks exactly, with less work. Chart JS is fairly opinionated in the look-and-feel that it provides, whereas Semiotic has more flexibility, so the latter may be required. However, Semiotic also has a steeper learning curve so may take more effort.

**Additional context**
N/A

**Comment by Wmaileq** [comment]
One question about projections and x axis on chart: should it be populated with months or years?
Maybe months should be used when 1,2 or 3 years used and years - when 4 or 5?

**Comment by jessex** [comment]
Good question and intuition, but no, this should always be populated with only years. Let's be consistent across the board.

**Comment by Wmaileq** [comment]
> Good question and intuition, but no, this should always be populated with only years. Let's be consistent across the board.

So, if 1 year projections chosen on chart will be only 2 points?
Or variant below?
![image](https://user-images.githubusercontent.com/26236198/93372429-904f0980-f85c-11ea-9894-2bc9bcbdff38.png)

**Comment by jessex** [comment]
Yeah I asked that same question in the PRD and Product confirmed that it would just be 2 data points in this case, so we just need to make sure that the styling scales well even when there are few data points.
