### ISSUE TITLE
Resolve vulnerability in ws package

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/supervision-success-component#64]
**What needs to be done? Why does it need to be done?**
The `ws` package, a transitive dependency of `react-scripts`, has a moderate severity vulnerability as documented [here](https://github.com/Recidiviz/supervision-success-component/security/dependabot/yarn.lock/ws/open). The package should be updated to a non-vulnerable version. (We may have to force a resolution, as we are restricted by the older version of react-scripts in use here.) 

**Additional context**
@jessex I don't believe there is any live vulnerability, because we don't use any websockets in the application, so I don't think it's urgent that we deploy anything to resolve this.

**Comment by jessex** [comment]
Sounds good here, too, @macfarlandian. Thanks! Ping me on the PR when it's ready.

**Comment by jessex** [comment]
That vulnerability has been inactive/outdated for a while now, closing this out.
