### ISSUE TITLE
Add support for displaying outcome proportions

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#70]
**Is your feature request related to a problem? Please describe.**
The PRD for the new V2 release of the app includes updated copy to make modeling changes more obvious.

**Describe the solution you'd like**
Implement the P2 feature in the "User Experience > Outcomes" section of the V2 PRD: "Below each outcome, add the proportion of it attributable to each slider (e.g., ‘400 fewer people in prison - 40% of that reduction is from revocations, 60% from new admissions)." This may require changes to the interface for working with the model to return this information. These numbers should always sum up to 100%.

**Describe alternatives you've considered**
N/A

**Additional context**
See the "User Experience > Outcomes" section of the V2 PRD.

**Comment by nasaownsky** [comment]
@jessex I don't exactly understand how to calculate this proportion. If they attributable to the sliders, then how they should sum up to 100%, if changes for example -40% from revocations  and -40% from new admissions?

**Comment by jessex** [comment]
So this is actually simpler than you think, @nasaownsky: we just need to look at the information that I think you're already sending to the Outcomes section on the left-hand side, and set the dynamic text based on the proportions of the overall change that are attributable to changes in revocations and changes in new admissions.

For example, if you look at this fake scenario:
<img width="1279" alt="Screen Shot 2021-07-14 at 11 14 21 AM" src="https://user-images.githubusercontent.com/431895/125664370-bbb2f9ac-7958-43ee-bc17-182a6642fbe1.png">

The outcomes on the left show a total reduction of 12155 people. If you play around with the sliders (e.g. set one of them to 0 and keep the other where it is), you can see that this is because there is a reduction of 336 for revocations and a reduction of 11818 for new admissions. So we'd say that (336 / 12155 = 2.76%) of that reduction is from revocations and (11818 / 12155 = 97.2%) of that reduction is from new admissions. Same goes for the reduced costs. Just take the two numbers you're already summing up, and calculate their proportions.
* Of course, in the example above, those two numbers of 336 and 11818 don't exactly add up to 12155 because there's some fraction rounding going on, so you want to make sure that the percentages add up to exactly 100% and that everything looks and feels consistent.
* Of course, you'd want to round the percentages to whole numbers as noted in the PRD, so it would be 3% and 97% for the above scenario, I believe.
* Finally, we need to make sure we handle the situation where one of the numbers increases and the other decreases. For example, if you drag the new revocations slider all the way to the right for "Yuta" but the new admissions slider all the way to the left, you get an overall decrease, a decrease in new admissions, but an increase in revocations.
  * I'm not exactly sure what we would want to display here.
  * @cawarren can you provide clarification? Maybe we'd just omit the one that has the smaller absolute value (revocations in this case) and say "100% of that reduction is from new admissions"? Or some other treatment?

**Comment by cawarren** [comment]
Yes, please go with Josh's suggestion if the impact is positive for one variable, and negative for the other: 
- Show '100% of the reduction is from [variable with the higher absolute value]'
- Don't show a % impact for the other variable

**Comment by nasaownsky** [comment]
So, two main issues: 
1. `New admissions` value is almost always more, than prison population diff. So I thought I can calculate the percentage for `Revocations` and then subtract it from 100 to get `New Admissions` proportion, but the second issue happened
2. `Revocations` value can also be more than prison population diff. 

<img width="1219" alt="Снимок экрана 2021-07-15 в 14 02 58" src="https://user-images.githubusercontent.com/20225344/125778667-61ecca72-0548-4fa1-aebd-030adec096fb.png">

What's your thoughts, guys? @jessex @cawarren

**Comment by jessex** [comment]
You've got the wrong numbers, @nasaownsky. In your scenario above, it shouldn't be 798 / 348. If you set that slider to 0, you see that the "starting" amount of revocations is 671. So now that it is 798, that means it has increased by 127. 127 / 348 is 36.5%. And for the other slider, if you set that to 0 you see it "starts" at 22580, so it has increased 221, so the proportion is 221 / 348 = 63.5%. And you can confirm the consistency there because the total outcome is 348 and 127 + 221 sums to that cleanly.

**Comment by nasaownsky** [comment]
Ahhh, I see now.
