### ISSUE TITLE
Upgrade normalize-url dependency

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#74]
**What needs to be done? Why does it need to be done?**
There is an active security vulnerability in the normalize-url dependency. This is a HIGH severity vulnerability and should be updated by Friday June 18th.

**Additional context**
[See the vulnerability here](https://github.com/Recidiviz/supervision-success-component/security/dependabot/yarn.lock/normalize-url/open)

**Comment by nasaownsky** [comment]
It seems like this vulnerability is coming from `react-scripts` package. The latest version of package is `4.0.3`, but the issue still isn't covered. See https://github.com/facebook/create-react-app/issues/11054 for information.

**Comment by jessex** [comment]
@nasaownsky can you solve this with a `resolutions` entry in the `package.json`? For example, to solve this in another repo of ours (for two different dependency vulnerabilities), we added:
```
"resolutions": {
    "**/glob-parent": "^5.1.2",
    "**/normalize-url": "^4.5.1"
}
```
