### ISSUE TITLE
Ensure browser compatibility for new version

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#86]
**What needs to be done? Why does it need to be done?**
Let's make sure that the app, after all of its recent updates, works effectively in the expected browsers:
- Chrome (latest version)
- Edge (latest version)
- Firefox (latest version)
- Safari (latest version)
- Internet Explorer 11
- Chrome on Android (latest version)
- Safari on iOS (latest version)

**Additional context**
If any issues are identified, fix them as part of this ticket. Otherwise, show screenshots from each browser as proof that we're in good shape.

**Comment by nasaownsky** [comment]
I haven't found any browser compatibility issues yet. Left this task open if something will be found.

**Comment by jessex** [comment]
I've used Browserstack Local to test this against all of the target environments and have found no compatibility issues, either!

The only thing I have noticed is something called out previously in https://github.com/Recidiviz/supervision-success-component/pull/84#issuecomment-885815565. On mobile (more precisely, skinnier viewports), while Chart.js will show the entire chart regardless of projection length, it will not consistently show all of the x-axis labels. Depending on projection length and width of the view-port, you may sometimes on mobile see all of the x-axis labels, you may sometimes see one or two, you may sometimes see the last year cut off on the right-hand side, it's a bit messy. @nasaownsky was not sure how to correct this in our last conversation.

@cawarren what do you think? Let me know if you need any more information.

**Comment by cawarren** [comment]
I think this is acceptable given the constraints of mobile viewports. No concerns from my side, thanks for checking @jessex

**Comment by jessex** [comment]
Thanks for confirming, @cawarren 🚀
