### ISSUE TITLE
Re-introduce use of 'Data Year' column for starting year

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/supervision-success-component#98]
**Is your feature request related to a problem? Please describe.**
In the original cost calculator, some data was from 2019 and other data was older (e.g., from 2017). To differentiate these, the second column of the params.csv file was `Data Year`, which included which year the data was from.

We've lost that in the update (this was our fault, in building the revised spreadsheet / inputs), and as a result we can't include several states that have older data. We should add this column back in, so that we can include those states with older data again.

**Describe the solution you'd like**
The `params.csv` file will be the same, but include a new column as the second column: `Data Year`.

The component should use this new column to update several strings in the UI:
- Under the state name selector, it should read "Based on [State Name] data from [`Data Year`], 2020". If 2020 data is not included, it should only mention the data year.
- Under the Outcomes section on the left, the string should read "From [Data Year] baseline"
- The X-axis should begin with the value in [Data Year], instead of "2019"

(I realize that last one might be visually confusing for someone, since the x-axis would say '2017   2020   2021   2022...', but I think that's an okay compromise to make.)

**Describe alternatives you've considered**
- We could continue to just stick with states that have 2019 data, but this leaves many states out of the calculator.
 
**Additional context**
An example `params` file is attached.
[params_revised.csv](https://github.com/Recidiviz/supervision-success-component/files/6972561/params_revised.csv)

Some clarifying points:
- 2020 should still be the 'special' year that projections jump off from, and that has the gray background if data is unavailable.
- The chart should pretend that years between the `Data Year` and 2020 don't exist (so the x-axis of the chart may go from 2017 to 2020 to 2021...)

**Comment by cawarren** [comment]
Note: This change includes two parts -
1. Updating the react component to accept new `params.csv` that includes the `Data Year` column as a newly inserted second column
2. Updating the UI strings as mentioned above

Nothing about the core model itself needs to change.

**Comment by jessex** [comment]
Caught up with @cawarren to confirm a couple of points:
- 2020 is still a "special" year in the app, i.e. it's still the year that projections are based off of. It's just that the year "to the left" of 2020 might not always be 2019 now. It might be 2017 or 2018.
- The chart should be unchanged except for the fact that the left-most data point might not be 2019 anymore. That is, regardless of whether data year is 2017, 2018, or 2019, that should be the left-most value on the x-axis, and then the next value should be 2020, the distance shouldn't scale to insert years in between.
